### ISSUE TITLE
Query Parameters

### ISSUE THREAD

**Issue by MakerScott** [ecrmnn/laravel-https#2]
Hi, it might be useful to allow query parameters to be passed on the redirect. Something like...

```            
$query = explode('?', $request->fullUrl());
if (isset($query[1])) {
    return redirect()->secure($request->path().'?'.$query[1]);
}
return redirect()->secure($request->path());
```

**Comment by ecrmnn** [comment]
This doesn't work now?
I don't think I've used it with query params my self.

Would be great if you could make a PR. Also remember to add a test for it. :)
