### ISSUE TITLE
Not working on Laravel 5.3

### ISSUE THREAD

**Issue by kanatkubash** [ecrmnn/laravel-https#3]
Hi thanks for this library.
I think you should change Laravel requirement to 5.4+ ,because method `Url::forceScheme` doesn't exist below L 5.4

**Comment by owenvoke** [comment]
I guess this could be resolved by adding either something like:
```php
method_exists($this->app['url'], 'forceScheme') ?
    $this->app['url']->forceScheme('https') :
    $this->app['url']->forceSchema('https');
```

In:
https://github.com/ecrmnn/laravel-https/blob/master/src/Providers/ServiceProvider.php#L16

Or, add `"illuminate/support": "^5.4"` in Composer. Which I think is neater and better going forward. 🤔

**Comment by kanatkubash** [comment]
Solved by adding `\Ecrmnn\LaravelHttps\Http\Middleware\ForceHttps::class` directly into web routes
